//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace TripolistMailAdapter.cn.tripolis.dialogue.contactGroup {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ContactGroupServiceSoapBinding", Namespace="http://contactgroup.services.tripolis.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceRequest))]
    public partial class ContactGroupService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private ResponseLanguage responseLanguageField;
        
        private AuthInfo authInfoField;
        
        private System.Threading.SendOrPostCallback addContactsToGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback getByContactDatabaseIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeAllContactsFromGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeContactsFromGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServiceInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getContactsOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback getByParentGroupIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ContactGroupService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::TripolistMailAdapter.Properties.Settings.Default.TripolistMailAdapter_cn_tripolis_dialogue_contactGroup_ContactGroupService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ResponseLanguage responseLanguage {
            get {
                return this.responseLanguageField;
            }
            set {
                this.responseLanguageField = value;
            }
        }
        
        public AuthInfo authInfo {
            get {
                return this.authInfoField;
            }
            set {
                this.authInfoField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event addContactsToGroupCompletedEventHandler addContactsToGroupCompleted;
        
        /// <remarks/>
        public event getByContactDatabaseIdCompletedEventHandler getByContactDatabaseIdCompleted;
        
        /// <remarks/>
        public event removeAllContactsFromGroupCompletedEventHandler removeAllContactsFromGroupCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        public event removeContactsFromGroupCompletedEventHandler removeContactsFromGroupCompleted;
        
        /// <remarks/>
        public event getServiceInfoCompletedEventHandler getServiceInfoCompleted;
        
        /// <remarks/>
        public event getByIdCompletedEventHandler getByIdCompleted;
        
        /// <remarks/>
        public event getContactsCompletedEventHandler getContactsCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event getByParentGroupIdCompletedEventHandler getByParentGroupIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse addContactsToGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ContactsToContactGroupRequest addContactsToGroupRequest) {
            object[] results = this.Invoke("addContactsToGroup", new object[] {
                        addContactsToGroupRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void addContactsToGroupAsync(ContactsToContactGroupRequest addContactsToGroupRequest) {
            this.addContactsToGroupAsync(addContactsToGroupRequest, null);
        }
        
        /// <remarks/>
        public void addContactsToGroupAsync(ContactsToContactGroupRequest addContactsToGroupRequest, object userState) {
            if ((this.addContactsToGroupOperationCompleted == null)) {
                this.addContactsToGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddContactsToGroupOperationCompleted);
            }
            this.InvokeAsync("addContactsToGroup", new object[] {
                        addContactsToGroupRequest}, this.addContactsToGroupOperationCompleted, userState);
        }
        
        private void OnaddContactsToGroupOperationCompleted(object arg) {
            if ((this.addContactsToGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addContactsToGroupCompleted(this, new addContactsToGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContactGroupListResponse getByContactDatabaseId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ContactGroupsByContactDatabaseIdRequest getByContactDatabaseIdRequest) {
            object[] results = this.Invoke("getByContactDatabaseId", new object[] {
                        getByContactDatabaseIdRequest});
            return ((ContactGroupListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getByContactDatabaseIdAsync(ContactGroupsByContactDatabaseIdRequest getByContactDatabaseIdRequest) {
            this.getByContactDatabaseIdAsync(getByContactDatabaseIdRequest, null);
        }
        
        /// <remarks/>
        public void getByContactDatabaseIdAsync(ContactGroupsByContactDatabaseIdRequest getByContactDatabaseIdRequest, object userState) {
            if ((this.getByContactDatabaseIdOperationCompleted == null)) {
                this.getByContactDatabaseIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByContactDatabaseIdOperationCompleted);
            }
            this.InvokeAsync("getByContactDatabaseId", new object[] {
                        getByContactDatabaseIdRequest}, this.getByContactDatabaseIdOperationCompleted, userState);
        }
        
        private void OngetByContactDatabaseIdOperationCompleted(object arg) {
            if ((this.getByContactDatabaseIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByContactDatabaseIdCompleted(this, new getByContactDatabaseIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse removeAllContactsFromGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] RemoveAllContactsRequest removeAllContactsFromGroupRequest) {
            object[] results = this.Invoke("removeAllContactsFromGroup", new object[] {
                        removeAllContactsFromGroupRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void removeAllContactsFromGroupAsync(RemoveAllContactsRequest removeAllContactsFromGroupRequest) {
            this.removeAllContactsFromGroupAsync(removeAllContactsFromGroupRequest, null);
        }
        
        /// <remarks/>
        public void removeAllContactsFromGroupAsync(RemoveAllContactsRequest removeAllContactsFromGroupRequest, object userState) {
            if ((this.removeAllContactsFromGroupOperationCompleted == null)) {
                this.removeAllContactsFromGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveAllContactsFromGroupOperationCompleted);
            }
            this.InvokeAsync("removeAllContactsFromGroup", new object[] {
                        removeAllContactsFromGroupRequest}, this.removeAllContactsFromGroupOperationCompleted, userState);
        }
        
        private void OnremoveAllContactsFromGroupOperationCompleted(object arg) {
            if ((this.removeAllContactsFromGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeAllContactsFromGroupCompleted(this, new removeAllContactsFromGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse update([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] UpdateContactGroupRequest updateRequest) {
            object[] results = this.Invoke("update", new object[] {
                        updateRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(UpdateContactGroupRequest updateRequest) {
            this.updateAsync(updateRequest, null);
        }
        
        /// <remarks/>
        public void updateAsync(UpdateContactGroupRequest updateRequest, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        updateRequest}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse create([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] CreateContactGroupRequest createRequest) {
            object[] results = this.Invoke("create", new object[] {
                        createRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(CreateContactGroupRequest createRequest) {
            this.createAsync(createRequest, null);
        }
        
        /// <remarks/>
        public void createAsync(CreateContactGroupRequest createRequest, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        createRequest}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse removeContactsFromGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ContactsToContactGroupRequest removeContactsFromGroupRequest) {
            object[] results = this.Invoke("removeContactsFromGroup", new object[] {
                        removeContactsFromGroupRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void removeContactsFromGroupAsync(ContactsToContactGroupRequest removeContactsFromGroupRequest) {
            this.removeContactsFromGroupAsync(removeContactsFromGroupRequest, null);
        }
        
        /// <remarks/>
        public void removeContactsFromGroupAsync(ContactsToContactGroupRequest removeContactsFromGroupRequest, object userState) {
            if ((this.removeContactsFromGroupOperationCompleted == null)) {
                this.removeContactsFromGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveContactsFromGroupOperationCompleted);
            }
            this.InvokeAsync("removeContactsFromGroup", new object[] {
                        removeContactsFromGroupRequest}, this.removeContactsFromGroupOperationCompleted, userState);
        }
        
        private void OnremoveContactsFromGroupOperationCompleted(object arg) {
            if ((this.removeContactsFromGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeContactsFromGroupCompleted(this, new removeContactsFromGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceResponse getServiceInfo() {
            object[] results = this.Invoke("getServiceInfo", new object[0]);
            return ((ServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getServiceInfoAsync() {
            this.getServiceInfoAsync(null);
        }
        
        /// <remarks/>
        public void getServiceInfoAsync(object userState) {
            if ((this.getServiceInfoOperationCompleted == null)) {
                this.getServiceInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServiceInfoOperationCompleted);
            }
            this.InvokeAsync("getServiceInfo", new object[0], this.getServiceInfoOperationCompleted, userState);
        }
        
        private void OngetServiceInfoOperationCompleted(object arg) {
            if ((this.getServiceInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServiceInfoCompleted(this, new getServiceInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContactGroupResponse getById([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] IDRequest getByIdRequest) {
            object[] results = this.Invoke("getById", new object[] {
                        getByIdRequest});
            return ((ContactGroupResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getByIdAsync(IDRequest getByIdRequest) {
            this.getByIdAsync(getByIdRequest, null);
        }
        
        /// <remarks/>
        public void getByIdAsync(IDRequest getByIdRequest, object userState) {
            if ((this.getByIdOperationCompleted == null)) {
                this.getByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByIdOperationCompleted);
            }
            this.InvokeAsync("getById", new object[] {
                        getByIdRequest}, this.getByIdOperationCompleted, userState);
        }
        
        private void OngetByIdOperationCompleted(object arg) {
            if ((this.getByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByIdCompleted(this, new getByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContactListResponse getContacts([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] GetByContactGroupIdRequest getContactsRequest) {
            object[] results = this.Invoke("getContacts", new object[] {
                        getContactsRequest});
            return ((ContactListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getContactsAsync(GetByContactGroupIdRequest getContactsRequest) {
            this.getContactsAsync(getContactsRequest, null);
        }
        
        /// <remarks/>
        public void getContactsAsync(GetByContactGroupIdRequest getContactsRequest, object userState) {
            if ((this.getContactsOperationCompleted == null)) {
                this.getContactsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetContactsOperationCompleted);
            }
            this.InvokeAsync("getContacts", new object[] {
                        getContactsRequest}, this.getContactsOperationCompleted, userState);
        }
        
        private void OngetContactsOperationCompleted(object arg) {
            if ((this.getContactsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getContactsCompleted(this, new getContactsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse delete([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] IDRequest deleteRequest) {
            object[] results = this.Invoke("delete", new object[] {
                        deleteRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(IDRequest deleteRequest) {
            this.deleteAsync(deleteRequest, null);
        }
        
        /// <remarks/>
        public void deleteAsync(IDRequest deleteRequest, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        deleteRequest}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://contactgroup.services.tripolis.com/", ResponseNamespace="http://contactgroup.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContactGroupListResponse getByParentGroupId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ContactGroupsByParentGroupIdRequest getByParentGroupIdRequest) {
            object[] results = this.Invoke("getByParentGroupId", new object[] {
                        getByParentGroupIdRequest});
            return ((ContactGroupListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getByParentGroupIdAsync(ContactGroupsByParentGroupIdRequest getByParentGroupIdRequest) {
            this.getByParentGroupIdAsync(getByParentGroupIdRequest, null);
        }
        
        /// <remarks/>
        public void getByParentGroupIdAsync(ContactGroupsByParentGroupIdRequest getByParentGroupIdRequest, object userState) {
            if ((this.getByParentGroupIdOperationCompleted == null)) {
                this.getByParentGroupIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByParentGroupIdOperationCompleted);
            }
            this.InvokeAsync("getByParentGroupId", new object[] {
                        getByParentGroupIdRequest}, this.getByParentGroupIdOperationCompleted, userState);
        }
        
        private void OngetByParentGroupIdOperationCompleted(object arg) {
            if ((this.getByParentGroupIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByParentGroupIdCompleted(this, new getByParentGroupIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tripolis.com/")]
    [System.Xml.Serialization.XmlRootAttribute("responseLanguage", Namespace="http://services.tripolis.com/", IsNullable=false)]
    public partial class ResponseLanguage : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tripolis.com/")]
    [System.Xml.Serialization.XmlRootAttribute("authInfo", Namespace="http://services.tripolis.com/", IsNullable=false)]
    public partial class AuthInfo : System.Web.Services.Protocols.SoapHeader {
        
        private string clientField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.services.tripolis.com/")]
    public partial class ContactField {
        
        private string idField;
        
        private string valueField;
        
        private string labelField;
        
        private string nameField;
        
        private string typeField;
        
        private bool keyField;
        
        private bool requiredField;
        
        private string contactDatabaseFieldGroupIdField;
        
        private int positionField;
        
        private kindOfField kindOfFieldField;
        
        private bool kindOfFieldFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactDatabaseFieldGroupId {
            get {
                return this.contactDatabaseFieldGroupIdField;
            }
            set {
                this.contactDatabaseFieldGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kindOfField kindOfField {
            get {
                return this.kindOfFieldField;
            }
            set {
                this.kindOfFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kindOfFieldSpecified {
            get {
                return this.kindOfFieldFieldSpecified;
            }
            set {
                this.kindOfFieldFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.services.tripolis.com/")]
    public enum kindOfField {
        
        /// <remarks/>
        GENERAL,
        
        /// <remarks/>
        SUMMARY,
        
        /// <remarks/>
        INTEREST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.services.tripolis.com/")]
    public partial class Contact {
        
        private string contactIdField;
        
        private ContactField[] contactFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contactField", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ContactField[] contactFields {
            get {
                return this.contactFieldsField;
            }
            set {
                this.contactFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.services.tripolis.com/")]
    public partial class ContactGroup {
        
        private string idField;
        
        private string labelField;
        
        private string nameField;
        
        private string typeField;
        
        private string parentGroupIdField;
        
        private System.DateTime modifiedAtField;
        
        private bool modifiedAtFieldSpecified;
        
        private bool isArchivedField;
        
        private KeyValuePair[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parentGroupId {
            get {
                return this.parentGroupIdField;
            }
            set {
                this.parentGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime modifiedAt {
            get {
                return this.modifiedAtField;
            }
            set {
                this.modifiedAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiedAtSpecified {
            get {
                return this.modifiedAtFieldSpecified;
            }
            set {
                this.modifiedAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isArchived {
            get {
                return this.isArchivedField;
            }
            set {
                this.isArchivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePair[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tripolis.com/")]
    public partial class KeyValuePair {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PageableListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SortableListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IDResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://response.services.tripolis.com/")]
    public partial class ServiceResponse {
        
        private string messageField;
        
        private KeyValuePair[] serviceInfoItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceInfoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePair[] serviceInfoItems {
            get {
                return this.serviceInfoItemsField;
            }
            set {
                this.serviceInfoItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SortableListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupListResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://response.services.tripolis.com/")]
    public partial class PageableListResponse : ServiceResponse {
        
        private PagingOut pagingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PagingOut paging {
            get {
                return this.pagingField;
            }
            set {
                this.pagingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://response.services.tripolis.com/")]
    public partial class PagingOut : PagingIn {
        
        private int totalItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int totalItems {
            get {
                return this.totalItemsField;
            }
            set {
                this.totalItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PagingOut))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://request.services.tripolis.com/")]
    public partial class PagingIn {
        
        private int pageNrField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageNr {
            get {
                return this.pageNrField;
            }
            set {
                this.pageNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupListResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://response.services.tripolis.com/")]
    public partial class SortableListResponse : PageableListResponse {
        
        private Sorting sortingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sorting sorting {
            get {
                return this.sortingField;
            }
            set {
                this.sortingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://request.services.tripolis.com/")]
    public partial class Sorting {
        
        private string sortByField;
        
        private string sortOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contact.services.tripolis.com/")]
    public partial class ContactListResponse : SortableListResponse {
        
        private Contact[] contactsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Contact[] contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contactgroup.services.tripolis.com/")]
    public partial class ContactGroupListResponse : SortableListResponse {
        
        private ContactGroup[] contactGroupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contactGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ContactGroup[] contactGroups {
            get {
                return this.contactGroupsField;
            }
            set {
                this.contactGroupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://response.services.tripolis.com/")]
    public partial class IDResponse : ServiceResponse {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contactgroup.services.tripolis.com/")]
    public partial class ContactGroupResponse : ServiceResponse {
        
        private ContactGroup contactGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContactGroup contactGroup {
            get {
                return this.contactGroupField;
            }
            set {
                this.contactGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contact.services.tripolis.com/")]
    public partial class ReturnContactFields {
        
        private string[] contactDatabaseFieldIdsField;
        
        private string[] contactDatabaseFieldNamesField;
        
        private string[] contactDatabaseFieldGroupIdsField;
        
        private string[] contactDatabaseFieldGroupNamesField;
        
        private bool returnAllContactFieldsField;
        
        private bool returnAllContactFieldsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contactDatabaseFieldId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] contactDatabaseFieldIds {
            get {
                return this.contactDatabaseFieldIdsField;
            }
            set {
                this.contactDatabaseFieldIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contactDatabaseFieldName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] contactDatabaseFieldNames {
            get {
                return this.contactDatabaseFieldNamesField;
            }
            set {
                this.contactDatabaseFieldNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contactDatabaseFieldGroupId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] contactDatabaseFieldGroupIds {
            get {
                return this.contactDatabaseFieldGroupIdsField;
            }
            set {
                this.contactDatabaseFieldGroupIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contactDatabaseFieldGroupName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] contactDatabaseFieldGroupNames {
            get {
                return this.contactDatabaseFieldGroupNamesField;
            }
            set {
                this.contactDatabaseFieldGroupNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool returnAllContactFields {
            get {
                return this.returnAllContactFieldsField;
            }
            set {
                this.returnAllContactFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnAllContactFieldsSpecified {
            get {
                return this.returnAllContactFieldsFieldSpecified;
            }
            set {
                this.returnAllContactFieldsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IDRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveAllContactsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PageableListRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SortableListRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetByContactGroupIdRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupsByParentGroupIdRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupsByContactDatabaseIdRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createServiceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateContactGroupRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateContactGroupRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactsToContactGroupRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://request.services.tripolis.com/")]
    public partial class ServiceRequest {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveAllContactsRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://request.services.tripolis.com/")]
    public partial class IDRequest : ServiceRequest {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contactgroup.services.tripolis.com/")]
    public partial class RemoveAllContactsRequest : IDRequest {
        
        private string referenceField;
        
        private string ipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SortableListRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetByContactGroupIdRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupsByParentGroupIdRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupsByContactDatabaseIdRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://request.services.tripolis.com/")]
    public partial class PageableListRequest : ServiceRequest {
        
        private PagingIn pagingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PagingIn paging {
            get {
                return this.pagingField;
            }
            set {
                this.pagingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetByContactGroupIdRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupsByParentGroupIdRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactGroupsByContactDatabaseIdRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://request.services.tripolis.com/")]
    public partial class SortableListRequest : PageableListRequest {
        
        private Sorting sortingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sorting sorting {
            get {
                return this.sortingField;
            }
            set {
                this.sortingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contact.services.tripolis.com/")]
    public partial class GetByContactGroupIdRequest : SortableListRequest {
        
        private string contactGroupIdField;
        
        private ReturnContactFields returnContactFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactGroupId {
            get {
                return this.contactGroupIdField;
            }
            set {
                this.contactGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReturnContactFields returnContactFields {
            get {
                return this.returnContactFieldsField;
            }
            set {
                this.returnContactFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contactgroup.services.tripolis.com/")]
    public partial class ContactGroupsByParentGroupIdRequest : SortableListRequest {
        
        private string parentGroupIdField;
        
        private groupType groupTypeField;
        
        private bool groupTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parentGroupId {
            get {
                return this.parentGroupIdField;
            }
            set {
                this.parentGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public groupType groupType {
            get {
                return this.groupTypeField;
            }
            set {
                this.groupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupTypeSpecified {
            get {
                return this.groupTypeFieldSpecified;
            }
            set {
                this.groupTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.services.tripolis.com/")]
    public enum groupType {
        
        /// <remarks/>
        STATIC,
        
        /// <remarks/>
        SUBSCRIPTION,
        
        /// <remarks/>
        TEST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contactgroup.services.tripolis.com/")]
    public partial class ContactGroupsByContactDatabaseIdRequest : SortableListRequest {
        
        private string contactDatabaseIdField;
        
        private groupType groupTypeField;
        
        private bool groupTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactDatabaseId {
            get {
                return this.contactDatabaseIdField;
            }
            set {
                this.contactDatabaseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public groupType groupType {
            get {
                return this.groupTypeField;
            }
            set {
                this.groupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupTypeSpecified {
            get {
                return this.groupTypeFieldSpecified;
            }
            set {
                this.groupTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateContactGroupRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contactgroup.services.tripolis.com/")]
    public abstract partial class createServiceRequest : ServiceRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contactgroup.services.tripolis.com/")]
    public partial class CreateContactGroupRequest : createServiceRequest {
        
        private string contactDatabaseIdField;
        
        private string labelField;
        
        private string nameField;
        
        private groupType groupTypeField;
        
        private string parentGroupIdField;
        
        private KeyValuePair[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactDatabaseId {
            get {
                return this.contactDatabaseIdField;
            }
            set {
                this.contactDatabaseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public groupType groupType {
            get {
                return this.groupTypeField;
            }
            set {
                this.groupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parentGroupId {
            get {
                return this.parentGroupIdField;
            }
            set {
                this.parentGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePair[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contactgroup.services.tripolis.com/")]
    public partial class UpdateContactGroupRequest : ServiceRequest {
        
        private string idField;
        
        private string labelField;
        
        private string nameField;
        
        private groupType groupTypeField;
        
        private bool groupTypeFieldSpecified;
        
        private string parentGroupIdField;
        
        private bool archivedField;
        
        private bool archivedFieldSpecified;
        
        private KeyValuePair[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public groupType groupType {
            get {
                return this.groupTypeField;
            }
            set {
                this.groupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupTypeSpecified {
            get {
                return this.groupTypeFieldSpecified;
            }
            set {
                this.groupTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parentGroupId {
            get {
                return this.parentGroupIdField;
            }
            set {
                this.parentGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool archived {
            get {
                return this.archivedField;
            }
            set {
                this.archivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool archivedSpecified {
            get {
                return this.archivedFieldSpecified;
            }
            set {
                this.archivedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePair[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contactgroup.services.tripolis.com/")]
    public partial class ContactsToContactGroupRequest : ServiceRequest {
        
        private string contactGroupIdField;
        
        private string[] contactIdsField;
        
        private string referenceField;
        
        private string ipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactGroupId {
            get {
                return this.contactGroupIdField;
            }
            set {
                this.contactGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contactId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] contactIds {
            get {
                return this.contactIdsField;
            }
            set {
                this.contactIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void addContactsToGroupCompletedEventHandler(object sender, addContactsToGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addContactsToGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addContactsToGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getByContactDatabaseIdCompletedEventHandler(object sender, getByContactDatabaseIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByContactDatabaseIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getByContactDatabaseIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactGroupListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactGroupListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void removeAllContactsFromGroupCompletedEventHandler(object sender, removeAllContactsFromGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeAllContactsFromGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeAllContactsFromGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void removeContactsFromGroupCompletedEventHandler(object sender, removeContactsFromGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeContactsFromGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeContactsFromGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getServiceInfoCompletedEventHandler(object sender, getServiceInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServiceInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServiceInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getByIdCompletedEventHandler(object sender, getByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactGroupResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactGroupResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getContactsCompletedEventHandler(object sender, getContactsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getContactsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getContactsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getByParentGroupIdCompletedEventHandler(object sender, getByParentGroupIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByParentGroupIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getByParentGroupIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactGroupListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactGroupListResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591