using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ChinaUnion_BO
{
    public class AgentFee
    {

        public String agentNo;
        public String agentFeeSeq;
        public String agentFeeMonth;
        public String feeName1;
        public String fee1;
        public String feeName2;
        public String fee2;
        public String feeName3;
        public String fee3;
        public String feeName4;
        public String fee4;
        public String feeName5;
        public String fee5;
        public String feeName6;
        public String fee6;
        public String feeName7;
        public String fee7;
        public String feeName8;
        public String fee8;
        public String feeName9;
        public String fee9;
        public String feeName10;
        public String fee10;
        public String feeName11;
        public String fee11;
        public String feeName12;
        public String fee12;
        public String feeName13;
        public String fee13;
        public String feeName14;
        public String fee14;
        public String feeName15;
        public String fee15;
        public String feeName16;
        public String fee16;
        public String feeName17;
        public String fee17;
        public String feeName18;
        public String fee18;
        public String feeName19;
        public String fee19;
        public String feeName20;
        public String fee20;
        public String feeName21;
        public String fee21;
        public String feeName22;
        public String fee22;
        public String feeName23;
        public String fee23;
        public String feeName24;
        public String fee24;
        public String feeName25;
        public String fee25;
        public String feeName26;
        public String fee26;
        public String feeName27;
        public String fee27;
        public String feeName28;
        public String fee28;
        public String feeName29;
        public String fee29;
        public String feeName30;
        public String fee30;
        public String feeName31;
        public String fee31;
        public String feeName32;
        public String fee32;
        public String feeName33;
        public String fee33;
        public String feeName34;
        public String fee34;
        public String feeName35;
        public String fee35;
        public String feeName36;
        public String fee36;
        public String feeName37;
        public String fee37;
        public String feeName38;
        public String fee38;
        public String feeName39;
        public String fee39;
        public String feeName40;
        public String fee40;
        public String feeName41;
        public String fee41;
        public String feeName42;
        public String fee42;
        public String feeName43;
        public String fee43;
        public String feeName44;
        public String fee44;
        public String feeName45;
        public String fee45;
        public String feeName46;
        public String fee46;
        public String feeName47;
        public String fee47;
        public String feeName48;
        public String fee48;
        public String feeName49;
        public String fee49;
        public String feeName50;
        public String fee50;   
        public String feeTotal;

        public Agent agent;
      

    }
}
