//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripolistMailAdapter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ContactGroupService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_contactGroup_ContactGroupService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_contactGroup_ContactGroupService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ContactService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_contact_ContactService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_contact_ContactService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/DirectEmailTypeService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_directEmailType_DirectEmailTypeService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_directEmailType_DirectEmailTypeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/DirectEmailService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_directEmail_DirectEmailService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_directEmail_DirectEmailService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/PublishingService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_publishing_PublishingService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_publishing_PublishingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ContactDatabaseFieldService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_contactDatabaseField_ContactDatabaseFieldService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_contactDatabaseField_ContactDatabaseFie" +
                    "ldService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/mtom/ExportService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_export_ExportService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_export_ExportService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ImportService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_import_ImportService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_import_ImportService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ContactDatabaseService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_contactDatabase_ContactDatabaseService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_contactDatabase_ContactDatabaseService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/WorkspaceService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_workspace_WorkspaceService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_workspace_WorkspaceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ReportingService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_reporting_ReportingService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_reporting_ReportingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/SubscriptionService")]
        public string TripolistMailAdapter_cn_tripolis_dialogue_subscription_SubscriptionService {
            get {
                return ((string)(this["TripolistMailAdapter_cn_tripolis_dialogue_subscription_SubscriptionService"]));
            }
        }
    }
}
