//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripolisDialogueAdapter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ContactDatabaseService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_contactDatabase_ContactDatabaseService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_contactDatabase_ContactDatabaseServi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ContactDatabaseFieldService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_contactDatabaseField_ContactDatabaseFieldService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_contactDatabaseField_ContactDatabase" +
                    "FieldService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ContactService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_contact_ContactService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_contact_ContactService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ContactGroupService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_contactGroup_ContactGroupService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_contactGroup_ContactGroupService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/WorkspaceService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_workspace_WorkspaceService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_workspace_WorkspaceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/DirectEmailTypeService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_directEmailType_DirectEmailTypeService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_directEmailType_DirectEmailTypeServi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/DirectEmailService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_directEmail_DirectEmailService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_directEmail_DirectEmailService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/PublishingService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_publish_PublishingService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_publish_PublishingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/SubscriptionService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_subscription_SubscriptionService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_subscription_SubscriptionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ReportingService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_reporting_ReportingService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_reporting_ReportingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/ImportService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_import_ImportService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_import_ImportService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/mtom/ExportService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_export_ExportService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_export_ExportService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/SmsTypeService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_smsType_SmsTypeService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_smsType_SmsTypeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dialogue.tripolis.cn/api2/soap/SmsMessageService")]
        public string TripolisDialogueAdapter_cn_tripolis_dialogue_smsMessage_SmsMessageService {
            get {
                return ((string)(this["TripolisDialogueAdapter_cn_tripolis_dialogue_smsMessage_SmsMessageService"]));
            }
        }
    }
}
