//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaUnion_Agent.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User Id=root;Host=115.29.229.134;Database=chinaunion;password=c513324665;charset=" +
            "utf8")]
        public string DBConnectString {
            get {
                return ((string)(this["DBConnectString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api@chinaunicom.cn")]
        public string TripoisUserName {
            get {
                return ((string)(this["TripoisUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test123")]
        public string TripolisPassword {
            get {
                return ((string)(this["TripolisPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("China Unicom")]
        public string TripolisClient {
            get {
                return ((string)(this["TripolisClient"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("agent@chinaunicom.cn")]
        public string MailFromAddress {
            get {
                return ((string)(this["MailFromAddress"]));
            }
            set {
                this["MailFromAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("agent@chinaunicom.cn")]
        public string MailReplyAddress {
            get {
                return ((string)(this["MailReplyAddress"]));
            }
            set {
                this["MailReplyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("上海联通")]
        public string MailSender {
            get {
                return ((string)(this["MailSender"]));
            }
            set {
                this["MailSender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("上海联通合作伙伴佣金告知单")]
        public string MailSubject {
            get {
                return ((string)(this["MailSubject"]));
            }
            set {
                this["MailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MjYxNTI2MTXJNzwjtk5i_w")]
        public string TripolisDBId {
            get {
                return ((string)(this["TripolisDBId"]));
            }
            set {
                this["TripolisDBId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MjA3NTIwNzVxWpsg5oprpg")]
        public string TripolisWorkspaceId {
            get {
                return ((string)(this["TripolisWorkspaceId"]));
            }
            set {
                this["TripolisWorkspaceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NjI4Mzk4NjJKsgFCFCvomQ")]
        public string TripolisDirectEmailId {
            get {
                return ((string)(this["TripolisDirectEmailId"]));
            }
            set {
                this["TripolisDirectEmailId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MTgzMjE4MzKEP3h36*317g")]
        public string TripolisEmailTypeId {
            get {
                return ((string)(this["TripolisEmailTypeId"]));
            }
            set {
                this["TripolisEmailTypeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wx4fe8b74e01fffcbb")]
        public string Wechat_Corpid {
            get {
                return ((string)(this["Wechat_Corpid"]));
            }
            set {
                this["Wechat_Corpid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ITnmki1ObPK9wNtPOaaCDkKb0VcEVMOf_IoLRaiGDQr6V_SZc9ZSOC1LdNSAuyyo")]
        public string Wechat_AgentSecret {
            get {
                return ((string)(this["Wechat_AgentSecret"]));
            }
            set {
                this["Wechat_AgentSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("佣金邮件已发送，请注意查收，你也可以通过微信企业号实时查收佣金情况,点击查询<a href=\"http://115.29.229.134/Wechat/Agent" +
            "FeeQuery.aspx?agentNo={0}&feeMonth={1}\">本月佣金详情</a>")]
        public string Wechat_Message {
            get {
                return ((string)(this["Wechat_Message"]));
            }
            set {
                this["Wechat_Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string Wecaht_Agent_Department {
            get {
                return ((string)(this["Wecaht_Agent_Department"]));
            }
            set {
                this["Wecaht_Agent_Department"] = value;
            }
        }
    }
}
