//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaUnion_Agent.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api@chinaunicom.cn")]
        public string TripoisUserName {
            get {
                return ((string)(this["TripoisUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test123")]
        public string TripolisPassword {
            get {
                return ((string)(this["TripolisPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("China Unicom")]
        public string TripolisClient {
            get {
                return ((string)(this["TripolisClient"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("agent@chinaunicom.cn")]
        public string MailFromAddress {
            get {
                return ((string)(this["MailFromAddress"]));
            }
            set {
                this["MailFromAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("agent@chinaunicom.cn")]
        public string MailReplyAddress {
            get {
                return ((string)(this["MailReplyAddress"]));
            }
            set {
                this["MailReplyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("上海联通")]
        public string MailSender {
            get {
                return ((string)(this["MailSender"]));
            }
            set {
                this["MailSender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("上海联通合作伙伴佣金告知单")]
        public string MailSubject {
            get {
                return ((string)(this["MailSubject"]));
            }
            set {
                this["MailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MjYxNTI2MTXJNzwjtk5i_w")]
        public string TripolisDBId {
            get {
                return ((string)(this["TripolisDBId"]));
            }
            set {
                this["TripolisDBId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MjA3NTIwNzVxWpsg5oprpg")]
        public string TripolisWorkspaceId {
            get {
                return ((string)(this["TripolisWorkspaceId"]));
            }
            set {
                this["TripolisWorkspaceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NjI4Mzk4NjJKsgFCFCvomQ")]
        public string TripolisDirectEmailId {
            get {
                return ((string)(this["TripolisDirectEmailId"]));
            }
            set {
                this["TripolisDirectEmailId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MTgzMjE4MzKEP3h36*317g")]
        public string TripolisEmailTypeId {
            get {
                return ((string)(this["TripolisEmailTypeId"]));
            }
            set {
                this["TripolisEmailTypeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wx31204de5a3ae758e")]
        public string Wechat_Corpid {
            get {
                return ((string)(this["Wechat_Corpid"]));
            }
            set {
                this["Wechat_Corpid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("佣金邮件已发送，请注意查收，你也可以通过微信企业号实时查收佣金情况,点击查询<a href=\"http://112.64.17.80/Wechat/AgentFe" +
            "eQuery.aspx?agentNo={0}&feeMonth={1}\">本月佣金详情</a>")]
        public string Wechat_Message {
            get {
                return ((string)(this["Wechat_Message"]));
            }
            set {
                this["Wechat_Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Wechat_Agent_Department {
            get {
                return ((int)(this["Wechat_Agent_Department"]));
            }
            set {
                this["Wechat_Agent_Department"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Wechat_Error_Department {
            get {
                return ((int)(this["Wechat_Error_Department"]));
            }
            set {
                this["Wechat_Error_Department"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stkc3kfO0sCrIJTFCHzOhmEsRWAnVGHqrzBIy4le6mV6EcSkNbpY0Tt49Uci2Buu")]
        public string Wechat_Secret {
            get {
                return ((string)(this["Wechat_Secret"]));
            }
            set {
                this["Wechat_Secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Wechat_Error_Sub_Department_1 {
            get {
                return ((int)(this["Wechat_Error_Sub_Department_1"]));
            }
            set {
                this["Wechat_Error_Sub_Department_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Wechat_Error_Sub_Department_2 {
            get {
                return ((int)(this["Wechat_Error_Sub_Department_2"]));
            }
            set {
                this["Wechat_Error_Sub_Department_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Wechat_Error_Sub_Department_3 {
            get {
                return ((int)(this["Wechat_Error_Sub_Department_3"]));
            }
            set {
                this["Wechat_Error_Sub_Department_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Wechat_Agent_AppId {
            get {
                return ((int)(this["Wechat_Agent_AppId"]));
            }
            set {
                this["Wechat_Agent_AppId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Wechar_Error_AppId {
            get {
                return ((int)(this["Wechar_Error_AppId"]));
            }
            set {
                this["Wechar_Error_AppId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NjUwMjk5NjXE_H8ej61hJQ")]
        public string TripolisEmailId {
            get {
                return ((string)(this["TripolisEmailId"]));
            }
            set {
                this["TripolisEmailId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("上海联通已经收到您的发票信息【收票日期：{0}，内容：{1}，金额：{2}，发票类型：{3}，发票号：{4}，备注：{5}】，您也可以通过微信企业号实时查询了解发" +
            "票接收情况。")]
        public string Invoice_Wechat_Message {
            get {
                return ((string)(this["Invoice_Wechat_Message"]));
            }
            set {
                this["Invoice_Wechat_Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("上海联通已经支付了一笔款项【处理时间：{0}，发票金额：{1}，付款金额：{2}，摘要：{3}，支付状态：{4}】，您也可以通过微信企业号实时查询了解支付情况。")]
        public string InvoicePayment_Wechat_Message {
            get {
                return ((string)(this["InvoicePayment_Wechat_Message"]));
            }
            set {
                this["InvoicePayment_Wechat_Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Wechar_Invoice_AppId {
            get {
                return ((int)(this["Wechar_Invoice_AppId"]));
            }
            set {
                this["Wechar_Invoice_AppId"] = value;
            }
        }
    }
}
