//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace TripolisDialogueAdapter.cn.tripolis.dialogue.workspace {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WorkspaceServiceSoapBinding", Namespace="http://workspace.services.tripolis.com/")]
    public partial class WorkspaceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private ResponseLanguage responseLanguageField;
        
        private AuthInfo authInfoField;
        
        private System.Threading.SendOrPostCallback getByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback copyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServiceInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback copyForContactDatabaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getByContactDatabaseIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WorkspaceService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::TripolisDialogueAdapter.Properties.Settings.Default.TripolisDialogueAdapter_cn_tripolis_dialogue_workspace_WorkspaceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ResponseLanguage responseLanguage {
            get {
                return this.responseLanguageField;
            }
            set {
                this.responseLanguageField = value;
            }
        }
        
        public AuthInfo authInfo {
            get {
                return this.authInfoField;
            }
            set {
                this.authInfoField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getByIdCompletedEventHandler getByIdCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event copyCompletedEventHandler copyCompleted;
        
        /// <remarks/>
        public event getServiceInfoCompletedEventHandler getServiceInfoCompleted;
        
        /// <remarks/>
        public event copyForContactDatabaseCompletedEventHandler copyForContactDatabaseCompleted;
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        public event getAllCompletedEventHandler getAllCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event getByContactDatabaseIdCompletedEventHandler getByContactDatabaseIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://workspace.services.tripolis.com/", ResponseNamespace="http://workspace.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorkspaceResponse getById([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] IDRequest getByIdRequest) {
            object[] results = this.Invoke("getById", new object[] {
                        getByIdRequest});
            return ((WorkspaceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getByIdAsync(IDRequest getByIdRequest) {
            this.getByIdAsync(getByIdRequest, null);
        }
        
        /// <remarks/>
        public void getByIdAsync(IDRequest getByIdRequest, object userState) {
            if ((this.getByIdOperationCompleted == null)) {
                this.getByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByIdOperationCompleted);
            }
            this.InvokeAsync("getById", new object[] {
                        getByIdRequest}, this.getByIdOperationCompleted, userState);
        }
        
        private void OngetByIdOperationCompleted(object arg) {
            if ((this.getByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByIdCompleted(this, new getByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://workspace.services.tripolis.com/", ResponseNamespace="http://workspace.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse delete([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] IDRequest deleteRequest) {
            object[] results = this.Invoke("delete", new object[] {
                        deleteRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(IDRequest deleteRequest) {
            this.deleteAsync(deleteRequest, null);
        }
        
        /// <remarks/>
        public void deleteAsync(IDRequest deleteRequest, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        deleteRequest}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://workspace.services.tripolis.com/", ResponseNamespace="http://workspace.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse copy([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] CopyWorkspaceRequest copyRequest) {
            object[] results = this.Invoke("copy", new object[] {
                        copyRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void copyAsync(CopyWorkspaceRequest copyRequest) {
            this.copyAsync(copyRequest, null);
        }
        
        /// <remarks/>
        public void copyAsync(CopyWorkspaceRequest copyRequest, object userState) {
            if ((this.copyOperationCompleted == null)) {
                this.copyOperationCompleted = new System.Threading.SendOrPostCallback(this.OncopyOperationCompleted);
            }
            this.InvokeAsync("copy", new object[] {
                        copyRequest}, this.copyOperationCompleted, userState);
        }
        
        private void OncopyOperationCompleted(object arg) {
            if ((this.copyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.copyCompleted(this, new copyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://workspace.services.tripolis.com/", ResponseNamespace="http://workspace.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceResponse getServiceInfo() {
            object[] results = this.Invoke("getServiceInfo", new object[0]);
            return ((ServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getServiceInfoAsync() {
            this.getServiceInfoAsync(null);
        }
        
        /// <remarks/>
        public void getServiceInfoAsync(object userState) {
            if ((this.getServiceInfoOperationCompleted == null)) {
                this.getServiceInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServiceInfoOperationCompleted);
            }
            this.InvokeAsync("getServiceInfo", new object[0], this.getServiceInfoOperationCompleted, userState);
        }
        
        private void OngetServiceInfoOperationCompleted(object arg) {
            if ((this.getServiceInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServiceInfoCompleted(this, new getServiceInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://workspace.services.tripolis.com/", ResponseNamespace="http://workspace.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse copyForContactDatabase([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] CopyWorkspaceForContactDatabaseRequest copyWorkspaceForContactDatabaseRequestRequest) {
            object[] results = this.Invoke("copyForContactDatabase", new object[] {
                        copyWorkspaceForContactDatabaseRequestRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void copyForContactDatabaseAsync(CopyWorkspaceForContactDatabaseRequest copyWorkspaceForContactDatabaseRequestRequest) {
            this.copyForContactDatabaseAsync(copyWorkspaceForContactDatabaseRequestRequest, null);
        }
        
        /// <remarks/>
        public void copyForContactDatabaseAsync(CopyWorkspaceForContactDatabaseRequest copyWorkspaceForContactDatabaseRequestRequest, object userState) {
            if ((this.copyForContactDatabaseOperationCompleted == null)) {
                this.copyForContactDatabaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OncopyForContactDatabaseOperationCompleted);
            }
            this.InvokeAsync("copyForContactDatabase", new object[] {
                        copyWorkspaceForContactDatabaseRequestRequest}, this.copyForContactDatabaseOperationCompleted, userState);
        }
        
        private void OncopyForContactDatabaseOperationCompleted(object arg) {
            if ((this.copyForContactDatabaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.copyForContactDatabaseCompleted(this, new copyForContactDatabaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://workspace.services.tripolis.com/", ResponseNamespace="http://workspace.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse create([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] CreateWorkspaceRequest createRequest) {
            object[] results = this.Invoke("create", new object[] {
                        createRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(CreateWorkspaceRequest createRequest) {
            this.createAsync(createRequest, null);
        }
        
        /// <remarks/>
        public void createAsync(CreateWorkspaceRequest createRequest, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        createRequest}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://workspace.services.tripolis.com/", ResponseNamespace="http://workspace.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorkspaceListResponse getAll([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ServiceRequest getAllRequest) {
            object[] results = this.Invoke("getAll", new object[] {
                        getAllRequest});
            return ((WorkspaceListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllAsync(ServiceRequest getAllRequest) {
            this.getAllAsync(getAllRequest, null);
        }
        
        /// <remarks/>
        public void getAllAsync(ServiceRequest getAllRequest, object userState) {
            if ((this.getAllOperationCompleted == null)) {
                this.getAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllOperationCompleted);
            }
            this.InvokeAsync("getAll", new object[] {
                        getAllRequest}, this.getAllOperationCompleted, userState);
        }
        
        private void OngetAllOperationCompleted(object arg) {
            if ((this.getAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllCompleted(this, new getAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://workspace.services.tripolis.com/", ResponseNamespace="http://workspace.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDResponse update([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] UpdateWorkspaceRequest updateRequest) {
            object[] results = this.Invoke("update", new object[] {
                        updateRequest});
            return ((IDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(UpdateWorkspaceRequest updateRequest) {
            this.updateAsync(updateRequest, null);
        }
        
        /// <remarks/>
        public void updateAsync(UpdateWorkspaceRequest updateRequest, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        updateRequest}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("authInfo")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseLanguage", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://workspace.services.tripolis.com/", ResponseNamespace="http://workspace.services.tripolis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorkspaceListResponse getByContactDatabaseId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ContactDatabaseIDRequest getByContactDatabaseIdRequest) {
            object[] results = this.Invoke("getByContactDatabaseId", new object[] {
                        getByContactDatabaseIdRequest});
            return ((WorkspaceListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getByContactDatabaseIdAsync(ContactDatabaseIDRequest getByContactDatabaseIdRequest) {
            this.getByContactDatabaseIdAsync(getByContactDatabaseIdRequest, null);
        }
        
        /// <remarks/>
        public void getByContactDatabaseIdAsync(ContactDatabaseIDRequest getByContactDatabaseIdRequest, object userState) {
            if ((this.getByContactDatabaseIdOperationCompleted == null)) {
                this.getByContactDatabaseIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByContactDatabaseIdOperationCompleted);
            }
            this.InvokeAsync("getByContactDatabaseId", new object[] {
                        getByContactDatabaseIdRequest}, this.getByContactDatabaseIdOperationCompleted, userState);
        }
        
        private void OngetByContactDatabaseIdOperationCompleted(object arg) {
            if ((this.getByContactDatabaseIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByContactDatabaseIdCompleted(this, new getByContactDatabaseIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tripolis.com/")]
    [System.Xml.Serialization.XmlRootAttribute("authInfo", Namespace="http://services.tripolis.com/", IsNullable=false)]
    public partial class AuthInfo : System.Web.Services.Protocols.SoapHeader {
        
        private string clientField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.services.tripolis.com/")]
    public partial class Workspace {
        
        private string idField;
        
        private string labelField;
        
        private string nameField;
        
        private string contactDatabaseIdField;
        
        private string publicDomainNameField;
        
        private string bounceDomainNameField;
        
        private bool listUnsubscribeHeaderField;
        
        private KeyValuePair[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactDatabaseId {
            get {
                return this.contactDatabaseIdField;
            }
            set {
                this.contactDatabaseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string publicDomainName {
            get {
                return this.publicDomainNameField;
            }
            set {
                this.publicDomainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bounceDomainName {
            get {
                return this.bounceDomainNameField;
            }
            set {
                this.bounceDomainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool listUnsubscribeHeader {
            get {
                return this.listUnsubscribeHeaderField;
            }
            set {
                this.listUnsubscribeHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePair[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tripolis.com/")]
    public partial class KeyValuePair {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IDResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkspaceListResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkspaceResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://response.services.tripolis.com/")]
    public partial class ServiceResponse {
        
        private string messageField;
        
        private KeyValuePair[] serviceInfoItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceInfoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePair[] serviceInfoItems {
            get {
                return this.serviceInfoItemsField;
            }
            set {
                this.serviceInfoItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://response.services.tripolis.com/")]
    public partial class IDResponse : ServiceResponse {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://workspace.services.tripolis.com/")]
    public partial class WorkspaceListResponse : ServiceResponse {
        
        private Workspace[] workspacesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("workspace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Workspace[] workspaces {
            get {
                return this.workspacesField;
            }
            set {
                this.workspacesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://workspace.services.tripolis.com/")]
    public partial class WorkspaceResponse : ServiceResponse {
        
        private Workspace workspaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Workspace workspace {
            get {
                return this.workspaceField;
            }
            set {
                this.workspaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactDatabaseIDRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IDRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateWorkspaceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createServiceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateWorkspaceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CopyWorkspaceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CopyWorkspaceForContactDatabaseRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://request.services.tripolis.com/")]
    public partial class ServiceRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://request.services.tripolis.com/")]
    public partial class ContactDatabaseIDRequest : ServiceRequest {
        
        private string contactDatabaseIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactDatabaseId {
            get {
                return this.contactDatabaseIdField;
            }
            set {
                this.contactDatabaseIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://request.services.tripolis.com/")]
    public partial class IDRequest : ServiceRequest {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://workspace.services.tripolis.com/")]
    public partial class UpdateWorkspaceRequest : ServiceRequest {
        
        private string idField;
        
        private string labelField;
        
        private string nameField;
        
        private string publicDomainNameField;
        
        private string bounceDomainNameField;
        
        private bool listUnsubscribeHeaderField;
        
        private bool listUnsubscribeHeaderFieldSpecified;
        
        private KeyValuePair[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string publicDomainName {
            get {
                return this.publicDomainNameField;
            }
            set {
                this.publicDomainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bounceDomainName {
            get {
                return this.bounceDomainNameField;
            }
            set {
                this.bounceDomainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool listUnsubscribeHeader {
            get {
                return this.listUnsubscribeHeaderField;
            }
            set {
                this.listUnsubscribeHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listUnsubscribeHeaderSpecified {
            get {
                return this.listUnsubscribeHeaderFieldSpecified;
            }
            set {
                this.listUnsubscribeHeaderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePair[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateWorkspaceRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://workspace.services.tripolis.com/")]
    public abstract partial class createServiceRequest : ServiceRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://workspace.services.tripolis.com/")]
    public partial class CreateWorkspaceRequest : createServiceRequest {
        
        private string contactDatabaseIdField;
        
        private string labelField;
        
        private string nameField;
        
        private string publicDomainNameField;
        
        private string bounceDomainNameField;
        
        private bool listUnsubscribeHeaderField;
        
        private KeyValuePair[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactDatabaseId {
            get {
                return this.contactDatabaseIdField;
            }
            set {
                this.contactDatabaseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string publicDomainName {
            get {
                return this.publicDomainNameField;
            }
            set {
                this.publicDomainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bounceDomainName {
            get {
                return this.bounceDomainNameField;
            }
            set {
                this.bounceDomainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool listUnsubscribeHeader {
            get {
                return this.listUnsubscribeHeaderField;
            }
            set {
                this.listUnsubscribeHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePair[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CopyWorkspaceForContactDatabaseRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://workspace.services.tripolis.com/")]
    public partial class CopyWorkspaceRequest : ServiceRequest {
        
        private string idField;
        
        private string userIdField;
        
        private string workspaceNameField;
        
        private string workspaceLabelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string workspaceName {
            get {
                return this.workspaceNameField;
            }
            set {
                this.workspaceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string workspaceLabel {
            get {
                return this.workspaceLabelField;
            }
            set {
                this.workspaceLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://workspace.services.tripolis.com/")]
    public partial class CopyWorkspaceForContactDatabaseRequest : CopyWorkspaceRequest {
        
        private string contactDatabaseNameField;
        
        private string contactDatabaseLabelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactDatabaseName {
            get {
                return this.contactDatabaseNameField;
            }
            set {
                this.contactDatabaseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactDatabaseLabel {
            get {
                return this.contactDatabaseLabelField;
            }
            set {
                this.contactDatabaseLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.tripolis.com/")]
    [System.Xml.Serialization.XmlRootAttribute("responseLanguage", Namespace="http://services.tripolis.com/", IsNullable=false)]
    public partial class ResponseLanguage : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getByIdCompletedEventHandler(object sender, getByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkspaceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkspaceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void copyCompletedEventHandler(object sender, copyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class copyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal copyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getServiceInfoCompletedEventHandler(object sender, getServiceInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServiceInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServiceInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void copyForContactDatabaseCompletedEventHandler(object sender, copyForContactDatabaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class copyForContactDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal copyForContactDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAllCompletedEventHandler(object sender, getAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkspaceListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkspaceListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getByContactDatabaseIdCompletedEventHandler(object sender, getByContactDatabaseIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByContactDatabaseIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getByContactDatabaseIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkspaceListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkspaceListResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591